pre_trained: True # scelgo con vero o falso se usare il modello pretrained e non
model_name: "TransUNet" #(TransUNet or NPTransUNet)
dataset_type: "Synapse" #scelgo che tipo di dataset usare. (Synapse, ACDC)

checkpoint_net: True # per settare l'utilizzo dei modelli pretrained presenti nella cartella PreTrainedModels
type_tr: "sgd"
lr: 0.01 #sennò 0.01
momentum: 0.9
weight_decay: 0.0001
batch: 24 # da valutare se 24 è troppo grande
n_iter_sy: 14000
n_iter_ACDC: 24000
n_epoch_sy: 152
num_workers: 4

seed: 123

image_size: 224
degrees: 20
flip_prob: 0.5
n_classes: 9

train_dir: "dataset/project_transunet/train_npz"
validation_dir: "dataset/project_transunet/validation_vol_h5"

log_every: 25
batch_window: 50
save_every: 19 # così otteniamo 8 checkpoint
checkpoint_dir: 'transunet_ckp_v3'
validation_frequency: 38 # valida ogni 8 epoche invece di ogni epoca (38 per testare in maniera veloce il modello)

save_dir: 'val_images'
resume: False # impostato così (True) indico di prendere l'ultimo checkpoint
validation: True #valutiamo la validation con [17] [19]

